services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cerverus
      POSTGRES_PASSWORD: cerverus
      POSTGRES_DB: cerverus
    ports:
      - "7654:5432"
  cerverus-back:
    build:
      context: .
      dockerfile: src/hosts/CerverusApi/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
    ports:
      - "5222:8080"
    environment:
      Backends__PostgresQL__Marten: "Host=postgres;Port=5432;Database=cerverus;Username=cerverus;Password=cerverus;Application Name=Cerverus Back Office;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - snapshots_volume:/app/Snapshots
  cerverus-ui:
    build:
      context: .
      dockerfile: src/hosts/CerverusUI/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:- Release}
    ports:
      - "666:8080"
    environment:
      Backend__Url: "http://cerverus-back:8080/api"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"

    depends_on:
      - cerverus-back
    volumes:
      - snapshots_volume:/app/Snapshots
volumes:
  snapshots_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Snapshots