services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cerverus
      POSTGRES_PASSWORD: cerverus
      POSTGRES_DB: cerverus
    ports:
      - "6543:5432"
  cerverus-back:
    build:
      context: .
      dockerfile: src/hosts/BackOfficeApi/Dockerfile
    ports:
        - "5222:8080"
    environment:
      Backends__PostgresQL__Marten: "Host=postgres;Port=5432;Database=cerverus;Username=cerverus;Password=cerverus;Application Name=Cerverus Back Office;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./Snapshots:/app/Snapshots