# This is a generated file. Not intended for manual editing.
services:
  cerverus-back:
    build:
      context: "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice"
      dockerfile: "src/hosts/CerverusApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "cerverusapi:dev"
    ports:
    - "127.0.0.1:54982:57100"
    - "127.0.0.1:57208:57300"
    volumes:
    - "C:\\Users\\dpina\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice\\src\\hosts\\CerverusApi:/app:rw"
    - "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice:/src:rw"
    - "C:\\Users\\dpina\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\dpina\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\dpina\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_10_14_02_05:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  cerverus-ui:
    build:
      context: "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice"
      dockerfile: "src/hosts/CerverusUI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/CerverusUI.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "cerverusui:dev"
    ports:
    - "127.0.0.1:54983:57100"
    - "127.0.0.1:57209:57300"
    volumes:
    - "C:\\Users\\dpina\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice\\src\\hosts\\CerverusUI:/app:rw"
    - "C:\\Users\\dpina\\RiderProjects\\cerverus-backoffice:/src:rw"
    - "C:\\Users\\dpina\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\dpina\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\dpina\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_10_14_02_05:/var/opt/rider-debugger:rw"
    working_dir: "/app"
